### ISSUE TITLE
Perform cleanup

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/charm-azure-integrator#14]
Any limited resources (service accounts, possibly custom roles, anything that can't be re-used by another instance of the charm) should be cleaned up at an appropriate time.

**Comment by johnsca** [comment]
Custom roles are re-used.  I'm not sure about cleaning up Managed Service Identities, whether it's necessary or a good idea.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809346.
