### ISSUE TITLE
pvc stuck in pending

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/charm-azure-integrator#16]
I followed the steps in the readme to create an SC and PVC:

https://github.com/juju-solutions/charm-azure-integrator#creating-a-pod-with-a-disk-storage-backed-volume

But the pvc stays in pending for well over an hour:
```bash
 kubectl describe sc
Name:                  azure-standard
IsDefaultClass:        No
Annotations:           <none>
Provisioner:           kubernetes.io/azure-disk
Parameters:            kind=shared,storageaccounttype=Standard_LRS
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>

$ kubectl get pvc testclaim
NAME        STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS     AGE
testclaim   Pending                                       azure-standard   84m
```

I can't find any logs from kubelet or kube-controller-manager related to a claim failure.  Then I stumbled across this bit about managed vs unmanaged disks:

https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/features.md#managed-disks-1

I'm reading between the lines here, but that makes me think `Standard_LRS` is only available with VMs that use *managed* storage.  When I did a `juju deploy canonical-kubernetes`, I apparently got machines that use *unmanaged* storage:

![screen shot 2018-08-30 at 12 27 43 pm](https://user-images.githubusercontent.com/4576822/44868332-2604a580-ac50-11e8-888d-1b8609f58144.png)

Any idea what's going on?  Is there a way to deploy CDK to azure using VMs with managed storage?

**Comment by kwmonroe** [comment]
Fwiw, this is an issue for me with both 1.12/beta and 1.11/stable with the following charm revisions:
```
azure-integrator                active      1  azure-integrator       jujucharms    0  ubuntu
easyrsa                3.0.1    active      1  easyrsa                jujucharms   87  ubuntu
etcd                   3.2.9    active      3  etcd                   jujucharms  160  ubuntu
flannel                0.10.0   active      5  flannel                jujucharms  109  ubuntu
kubeapi-load-balancer  1.10.3   active      1  kubeapi-load-balancer  jujucharms  117  ubuntu  exposed
kubernetes-master      1.11.2   active      2  kubernetes-master      jujucharms  172  ubuntu
kubernetes-worker      1.11.2   active      3  kubernetes-worker      jujucharms  193  ubuntu  exposed
```

**Comment by ivanhitos-canonical** [comment]
I can confirm that I can see a similar issue. My disks are 'managed disks' though.

$ kubectl describe pvc
Name:          testclaim
Namespace:     default
StorageClass:  azure-standard
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/azure-disk
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
Events:
  Type     Reason              Age                 From                         Message
  ----     ------              ----                ----                         -------
  Warning  ProvisioningFailed  48m                 persistentvolume-controller  Failed to provision volume with StorageClass "azure-standard": Create Storage Account: xxxxx, error: storage.AccountsClient#Create: Failure sending request: StatusCode=403 -- Original Error: Code="AuthorizationFailed" Message="The client 'aaaaa-bbbb-ccc-dddd-eee' with object id 'ffff-gggg-hhhh-iiiiii-jjjjj' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/write' over scope '/subscriptions/kkkkkk-llll-mmmm-nnnnn-ooooo/resourceGroups/test-resourceGroup/providers/Microsoft.Storage/storageAccounts/pppppp'."
.....
.....

**Comment by johnsca** [comment]
Per https://kubernetes.io/docs/concepts/storage/storage-classes/#new-azure-disk-storage-class-starting-from-v1-7-2 both the `storageaccounttype` and `kind` values depend on the type of VM provisioned.

`Standard_LRS` should work on either Premium or Standard VMs, and `kind: shared` should make it use unmanaged disks, which should work on unmanaged VMs.  However, it's missing the permission to manage the storage accounts for unmanaged disks.

Fixing that, I still get an error about "invalid disk URI" after creating the disk.

**Comment by johnsca** [comment]
I'm also not sure how to verify or influence whether we got a managed or unmanaged VM.

**Comment by johnsca** [comment]
It seems that Juju was creating managed VMs, so the only change needed is to replace `kind: shared` with `kind: managed`.
