### ISSUE TITLE
Add support for Azure CNI Plugin

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/charm-azure-integrator#2]
Hey,

Missing integration with Azure CNI plugin for native Azure network configuration options, can we please have this added to the CDK bundle as customers are requesting this? 

Cheers

**Comment by johnsca** [comment]
Yes, that's the intention, but it's not quite complete.

**Comment by johnsca** [comment]
I've added issues for all of the features still needed to make it work with k8s.  I also put up an in-progress PR with my current work for the first of those.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809345.
